title : "Language, Action and Perception (APL-ESSLLI) - Tutorials"
description : "Introductory Course in Language and Computation at ESSLLI 2019,
Week 2, 17:00 - 18:30, 12 - 16 August, University of Latvia, Riga, Latvia"
